// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NaukriScraperApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250806103148_added userID to resume")]
    partial class addeduserIDtoresume
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NaukriScraperApi.Model.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GraduationYear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PercentageOrCgpa")
                        .HasColumnType("double");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserResumeId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("CurrentlyWorking")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserResumeId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.JobDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("MatchScore")
                        .HasColumnType("double");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("companyName")
                        .HasColumnType("longtext");

                    b.Property<string>("experienceRequired")
                        .HasColumnType("longtext");

                    b.Property<string>("isApplied")
                        .HasColumnType("longtext");

                    b.Property<string>("jobDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("jobId")
                        .HasColumnType("longtext");

                    b.Property<string>("jobTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("link")
                        .HasColumnType("longtext");

                    b.Property<string>("location")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobDetails");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TechnologiesUsed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserResumeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.TokenSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JtiHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TokenSessions");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleId")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isNaukriLoggedIn")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrentCompany")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrentJobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentSalary")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedSalary")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("HighestQualification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredJobRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimarySkills")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Projects")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecondarySkills")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalExperience")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserProfileSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float?>("XIIPercentage")
                        .HasColumnType("float");

                    b.Property<float?>("XPercentage")
                        .HasColumnType("float");

                    b.Property<string>("noticePeriod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("willingToRelocate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.UserResume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserResumes");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.Education", b =>
                {
                    b.HasOne("NaukriScraperApi.Model.UserResume", "UserResume")
                        .WithMany("Education")
                        .HasForeignKey("UserResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserResume");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.Job", b =>
                {
                    b.HasOne("NaukriScraperApi.Model.UserResume", "UserResume")
                        .WithMany("Jobs")
                        .HasForeignKey("UserResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserResume");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.JobDetails", b =>
                {
                    b.HasOne("NaukriScraperApi.Model.User", "User")
                        .WithMany("JobApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.Project", b =>
                {
                    b.HasOne("NaukriScraperApi.Model.UserResume", "UserResume")
                        .WithMany("Projects")
                        .HasForeignKey("UserResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserResume");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.UserProfile", b =>
                {
                    b.HasOne("NaukriScraperApi.Model.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("NaukriScraperApi.Model.UserProfile", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.User", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("NaukriScraperApi.Model.UserResume", b =>
                {
                    b.Navigation("Education");

                    b.Navigation("Jobs");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
